# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ddm.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ddm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tddm.proto\x12\x02pb\"\xdb\x03\n\x07\x44\x44MData\x12\x14\n\x0cmachine_time\x18\x01 \x02(\x01\x12\x10\n\x08sim_time\x18\x02 \x02(\x01\x12$\n\x08sim_vars\x18\x03 \x03(\x0b\x32\x12.pb.DDMData.SimVar\x12\x14\n\x0cis_start_sim\x18\x04 \x01(\x08\x12\x13\n\x0bis_stop_sim\x18\x05 \x01(\x08\x12\"\n\x07tm_vars\x18\x06 \x03(\x0b\x32\x11.pb.DDMData.TmVar\x12\"\n\x07\x66\x63_vars\x18\x07 \x03(\x0b\x32\x11.pb.DDMData.FcVar\x1a\xc3\x01\n\x06SimVar\x12\x0c\n\x04name\x18\x01 \x02(\t\x12%\n\x04type\x18\x02 \x02(\x0e\x32\x17.pb.DDMData.SimVar.Type\x12\x14\n\x0c\x64ouble_value\x18\x03 \x01(\x01\x12\x11\n\tint_value\x18\x04 \x01(\x01\x12\x12\n\nbool_value\x18\x05 \x01(\x01\x12\x14\n\x0cstring_value\x18\x06 \x01(\t\"1\n\x04Type\x12\x08\n\x04\x42ool\x10\x01\x12\x07\n\x03Int\x10\x02\x12\n\n\x06\x44ouble\x10\x03\x12\n\n\x06String\x10\x04\x1a$\n\x05TmVar\x12\x0c\n\x04\x63ode\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\x01\x1a#\n\x05\x46\x63Var\x12\x0c\n\x04\x63ode\x18\x01 \x02(\t\x12\x0c\n\x04time\x18\x02 \x02(\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ddm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DDMDATA']._serialized_start=18
  _globals['_DDMDATA']._serialized_end=493
  _globals['_DDMDATA_SIMVAR']._serialized_start=223
  _globals['_DDMDATA_SIMVAR']._serialized_end=418
  _globals['_DDMDATA_SIMVAR_TYPE']._serialized_start=369
  _globals['_DDMDATA_SIMVAR_TYPE']._serialized_end=418
  _globals['_DDMDATA_TMVAR']._serialized_start=420
  _globals['_DDMDATA_TMVAR']._serialized_end=456
  _globals['_DDMDATA_FCVAR']._serialized_start=458
  _globals['_DDMDATA_FCVAR']._serialized_end=493
# @@protoc_insertion_point(module_scope)
